export const spacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  base: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  screen: 24,
  '3xl': 40,
  '4xl': 48,
  '5xl': 64,
} as const;

export type SpacingToken = keyof typeof spacing;

export const layout = {
  screenPaddingX: spacing.xl,
  sectionGap: spacing.xxl,
  ctaHeight: 60,
  inputHeight: 56,
  tabBarHeight: 68,
  headerHeight: 56,
  segmentHeight: 36,
  memberSignalHeight: 120,
  inlineButtonHeight: 44,
  profileCardHeight: 96,
  avatarSm: 32,
  avatarMd: 48,
  avatarOverlap: 20,
  avatarOverlapTight: 14,
  moodDot: 26,
  illustrationSlot: 120,
  timelineGutter: 24,
  timelineDot: 10,
  rowHeight: 56,
  maxContentWidth: 640,
} as const;
